apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "capi-test"
  namespace: "default"
spec:
  clusterNetwork:
    services:
      cidrBlocks: [10.96.0.0/12]
    pods:
      cidrBlocks: [192.168.0.0/16]
    serviceDomain: k8s.test
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
      - name: etcdImageTag
        value: ""
      - name: coreDNSImageTag
        value: ""
      - name: podSecurityStandard
        value:
          enabled: true
          enforce: "baseline"
          audit: "restricted"
          warn: "restricted"
    version: v1.27.1
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
---
